---

- debug: 
    msg: "{{ users }}"

- debug: 
    msg: "{{ item.username }} {{ item.pw_hash }}"
  loop: "{{ users }}"

- name: setup users deb
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    groups: sudo
    password: "{{ item.pw_hash }}"
    append: yes
  loop: "{{ users }}"
  when: ansible_facts['os_family'] == "Debian"

- name: setup users rhel
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    groups: wheel
    password: "{{ item.pw_hash }}"
    append: yes
  loop: "{{ users }}"
  when: ansible_facts['os_family'] == "RedHat"

- name: create .ssh folder
  file:
    path: /home/nagel/.ssh
    owner: nagel
    group: nagel
    mode: 0700
    state: directory

- name: create authorized_keys
  authorized_key:
    user: nagel
    state: present
    key: "{{ lookup('file', 'roles/user-setup/files/{{ item.username }}-authorized_keys') }}"
  loop: "{{ users }}"