---

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install required system packages Debian
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3', 'python3-pip', 'virtualenv', 'python3-setuptools']
  when: ansible_facts['os_family'] == "Debian"

- name: Install required system packages RHEL
  dnf: 
    name: "{{ item }}"
    state: present
  loop: ['yum-utils', 'epel-release', 'device-mapper-persistent-data', 'lvm2', 'curl', 'python3', 'python3-pip', 'libselinux-python3']
  when: ansible_facts['os_family'] == "RedHat"


- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker Repository Deb
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker Repository RHEL
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: ansible_facts['os_family'] == "RedHat"

- name: Update apt
  apt: update_cache=yes
  when: ansible_facts['os_family'] == "Debian"

- name: install docker-ce
  package: 
    name: docker-ce
    state: present

- name: Install Docker Module for Python
  command: pip3 install docker

- name: install docker-compose
  command: pip3 install docker-compose

- name: systemd for docker
  systemd:
    name: docker
    enabled: yes
    state: started
    
- name: add users to docker group
  user: 
    name: "{{ item.username }}"
    groups: docker
    append: yes
  when: item.use_docker
  loop: "{{ users }}"